
on: push

name: Tests

jobs:
    testAll:
        
        name: All Unit Tests
        runs-on: ubuntu-latest
        
        steps:
        
        -   uses: actions/checkout@master
        
        -   uses: denoland/setup-deno@v1
            with:
                deno-version: vx.x.x
        
        -   run: Tools/Test.ts
