on: push
name: Tests
jobs:
  testAll:
    name: test all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.38.0
      - run: deno test -A tokenizer_test.ts
        
