on: push
name: Tests
jobs:
  testAll:
    name: test all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.41.0
      - run: deno test
